---

namespace: "zephyr82"
name: "fhem"
version: "0.0.3"
readme: README.md
authors:
  - Zephyr82 github.com/zephyr82

description: a collection for installation, backuping up and restoring of a FHEM home automation server
license_file: LICENSE

tags: ["tools"]
dependencies:
  "ansible.utils": "*" # note: "*" selects the latest version available

repository: https://github.com/Zephyr82/ansible-collection-fhem

build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
