---
# tasks file for zephyr82.fhem.installation

- name: Include OS specific installation tasks
  ansible.builtin.include_tasks:
    file: "installation/{{ ansible_facts['os_family'] }}.yml"
  tags:
    - fhem_installation
